name: Sync File to Website

on:
  push:
    branches:
      - master # Déclenche le script dès que vous poussez des changements sur la branche main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Repo
      uses: actions/checkout@v4

    - name: Pousser le fichier vers le site web
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'report_damien_junger.pdf' # À MODIFIER : Le fichier à copier dans le Dossier A
        destination_repo: 'grenadinelas/site-web' # À MODIFIER : Le dépôt du Dossier B
        destination_folder: 'Desktop/site web/pdf' # À MODIFIER : Où placer le fichier dans le site web (laisser vide '' pour la racine)
        user_email: 'damien.junger1@gmail.com' # À MODIFIER
        user_name: 'grenadinelas' # À MODIFIER
        commit_message: 'Mise à jour automatique du fichier depuis le dépôt source'
